use crate::ast::{Document, Enum, Field, Function, Service, ServiceItem, Store, Type, TypeAlias};

pub fn generate_rust(document: &Document) -> String {
    generate_rust_with_mode(document, RustMode::Both)
}

pub fn generate_rust_with_mode(document: &Document, mode: RustMode) -> String {
    RustGenerator::new(document, mode).generate()
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RustMode {
    Client,
    Server,
    Both,
}

impl RustMode {
    fn includes_client(self) -> bool {
        matches!(self, Self::Client | Self::Both)
    }

    fn includes_server(self) -> bool {
        matches!(self, Self::Server | Self::Both)
    }
}

struct RustGenerator<'a> {
    document: &'a Document,
    mode: RustMode,
    out: String,
}

impl<'a> RustGenerator<'a> {
    fn new(document: &'a Document, mode: RustMode) -> Self {
        Self {
            document,
            mode,
            out: String::new(),
        }
    }

    fn generate(mut self) -> String {
        self.line("// Generated by midl. Do not edit by hand.");
        self.line("#[allow(dead_code, non_snake_case, unused_imports, unused_variables)]");
        self.line("const _: () = ();");
        self.line("");
        self.line("pub type BindingResult<T> = Result<T, BindingError>;");
        if self.mode.includes_server() {
            self.line("use motherboard_client::{ServerApi as _, ServerStoresApi as _};");
            self.line(
                "type AnonymousStoreAuthorizer = std::sync::Arc<dyn Fn(motherboard_client::Origin) -> bool + Send + Sync>;",
            );
        }
        self.line("");
        self.line("#[derive(Debug)]");
        self.line("pub enum BindingError {");
        self.line("    Client(motherboard_client::ClientError),");
        self.line("    Encode(postcard::Error),");
        self.line("    Decode(postcard::Error),");
        self.line("    UnexpectedReply,");
        self.line("}");
        self.line("");
        self.line("impl From<motherboard_client::ClientError> for BindingError {");
        self.line(
            "    fn from(error: motherboard_client::ClientError) -> Self { Self::Client(error) }",
        );
        self.line("}");
        self.line("");
        self.line("impl core::fmt::Display for BindingError {");
        self.line("    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {");
        self.line("        match self {");
        self.line("            Self::Client(error) => write!(f, \"client error: {error}\"),");
        self.line("            Self::Encode(error) => write!(f, \"encode error: {error}\"),");
        self.line("            Self::Decode(error) => write!(f, \"decode error: {error}\"),");
        self.line("            Self::UnexpectedReply => write!(f, \"unexpected reply\"),");
        self.line("        }");
        self.line("    }");
        self.line("}");
        self.line("");
        self.line("impl std::error::Error for BindingError {}");
        self.line("");
        self.line("pub struct AnonymousStore<T> {");
        self.line("    pub id: motherboard_client::AnonymousStoreId,");
        self.line("    _marker: core::marker::PhantomData<fn() -> T>,");
        self.line("}");
        self.line("");
        self.line("impl<T> AnonymousStore<T> {");
        self.line("    pub fn new(id: motherboard_client::AnonymousStoreId) -> Self {");
        self.line("        Self { id, _marker: core::marker::PhantomData }");
        self.line("    }");
        self.line("}");
        self.line("");
        self.line("impl<T> Clone for AnonymousStore<T> {");
        self.line("    fn clone(&self) -> Self { *self }");
        self.line("}");
        self.line("");
        self.line("impl<T> Copy for AnonymousStore<T> {}");
        self.line("");
        self.line("impl<T> core::fmt::Debug for AnonymousStore<T> {");
        self.line("    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {");
        self.line("        f.debug_tuple(\"AnonymousStore\").field(&self.id).finish()");
        self.line("    }");
        self.line("}");
        self.line("");
        self.line("impl<T> PartialEq for AnonymousStore<T> {");
        self.line("    fn eq(&self, other: &Self) -> bool { self.id == other.id }");
        self.line("}");
        self.line("");
        self.line("impl<T> Eq for AnonymousStore<T> {}");
        self.line("");
        self.line("impl<T> serde::Serialize for AnonymousStore<T> {");
        self.line("    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>");
        self.line("    where");
        self.line("        S: serde::Serializer,");
        self.line("    {");
        self.line("        <motherboard_client::AnonymousStoreId as serde::Serialize>::serialize(&self.id, serializer)");
        self.line("    }");
        self.line("}");
        self.line("");
        self.line("impl<'de, T> serde::Deserialize<'de> for AnonymousStore<T> {");
        self.line("    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>");
        self.line("    where");
        self.line("        D: serde::Deserializer<'de>,");
        self.line("    {");
        self.line("        Ok(Self::new(<motherboard_client::AnonymousStoreId as serde::Deserialize>::deserialize(deserializer)?))");
        self.line("    }");
        self.line("}");
        self.line("");

        for service in &self.document.services {
            self.service(service);
        }

        if self.mode.includes_server() {
            self.server_runtime();
        }

        self.out
    }

    fn service(&mut self, service: &Service) {
        self.docs(&service.docs, 0);
        self.line(&format!("pub mod {} {{", snake_case(&service.name)));
        self.line("    use motherboard_client::{ClientApi as _, ClientCallsApi as _, ClientStoresApi as _, ServerApi as _, ServerCallsApi as _, ServerStoresApi as _};");
        self.line("    use super::{AnonymousStore, BindingError, BindingResult};");
        self.line("");
        self.line(&format!(
            "    pub const SERVICE: &str = {:?};",
            service.name
        ));
        self.line("");

        for item in &service.items {
            match item {
                ServiceItem::TypeAlias(alias) => self.type_alias(alias),
                ServiceItem::Enum(enm) => self.enum_def(enm),
                ServiceItem::Store(store) => self.store_const(store),
                ServiceItem::Function(function) => self.function_error(function),
            }
        }

        if self.mode.includes_client() {
            self.client_wrapper(service);
        }
        if self.mode.includes_server() {
            self.server_wrapper(service);
            self.request_enum(service);
        }
        if self.mode.includes_client() {
            self.reply_decoders(service);
        }
        self.line("}");
        self.line("");
    }

    fn type_alias(&mut self, alias: &TypeAlias) {
        self.docs_indented(&alias.docs, 4);
        self.line(&format!(
            "    pub type {} = {};",
            alias.name,
            rust_type(&alias.ty)
        ));
        self.line("");
    }

    fn enum_def(&mut self, enm: &Enum) {
        self.docs_indented(&enm.docs, 4);
        self.line("    #[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]");
        self.line(&format!("    pub enum {} {{", enm.name));
        for variant in &enm.variants {
            self.docs_indented(&variant.docs, 8);
            if variant.fields.is_empty() {
                self.line(&format!("        {},", variant.name));
            } else {
                self.line(&format!("        {} {{", variant.name));
                for field in &variant.fields {
                    self.line(&format!(
                        "            {}: {},",
                        field.name,
                        rust_type(&field.ty)
                    ));
                }
                self.line("        },");
            }
        }
        self.line("    }");
        self.line("");
    }

    fn store_const(&mut self, store: &Store) {
        self.docs_indented(&store.docs, 4);
        self.line(&format!(
            "    pub const {}_STORE: &str = {:?};",
            screaming_snake_case(&store.name),
            store.name
        ));
        self.line(&format!(
            "    pub const {}_STORE_PUBLIC: bool = {};",
            screaming_snake_case(&store.name),
            store.public
        ));
        self.line("");
    }

    fn function_error(&mut self, function: &Function) {
        if function.errors.is_empty() {
            return;
        }
        let name = format!("{}Error", pascal_case(&function.name));
        self.line(
            "    #[derive(Clone, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]",
        );
        self.line(&format!("    pub enum {name} {{"));
        for error in &function.errors {
            self.line(&format!("        {error},"));
        }
        self.line("    }");
        self.line("");
        self.line(&format!("    impl {name} {{"));
        self.line("        pub fn code(&self) -> &'static str {");
        self.line("            match self {");
        for error in &function.errors {
            self.line(&format!("                Self::{error} => {:?},", error));
        }
        self.line("            }");
        self.line("        }");
        self.line("");
        self.line("        pub fn from_code(code: &str) -> Option<Self> {");
        self.line("            match code {");
        for error in &function.errors {
            self.line(&format!(
                "                {:?} => Some(Self::{error}),",
                error
            ));
        }
        self.line("                _ => None,");
        self.line("            }");
        self.line("        }");
        self.line("    }");
        self.line("");
        self.line(&format!("    impl core::fmt::Display for {name} {{"));
        self.line("        fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {");
        self.line("            f.write_str(self.code())");
        self.line("        }");
        self.line("    }");
        self.line("");
        self.line(&format!("    impl std::error::Error for {name} {{}}"));
        self.line("");
    }

    fn client_wrapper(&mut self, service: &Service) {
        self.line("    type ReplyCache = std::sync::Arc<tokio::sync::Mutex<std::collections::HashMap<motherboard_client::RequestId, motherboard_client::InboxMessage>>>;");
        self.line("    type MessageQueue = std::sync::Arc<tokio::sync::Mutex<std::collections::VecDeque<motherboard_client::InboxMessage>>>;");
        self.line("");
        self.line("    struct ClientState {");
        self.line("        motherboard: std::sync::Arc<motherboard_client::MotherboardClient>,");
        self.line("        fetch_lock: std::sync::Arc<tokio::sync::Mutex<()>>,");
        self.line("        replies: ReplyCache,");
        self.line("        messages: MessageQueue,");
        self.line("    }");
        self.line("");
        self.line("    impl ClientState {");
        self.line("        fn open() -> BindingResult<Self> {");
        self.line("            Ok(Self {");
        self.line("                motherboard: std::sync::Arc::new(motherboard_client::MotherboardClient::open().map_err(motherboard_client::ClientError::Io)?),");
        self.line("                fetch_lock: Default::default(),");
        self.line("                replies: Default::default(),");
        self.line("                messages: Default::default(),");
        self.line("            })");
        self.line("        }");
        self.line("    }");
        self.line("");
        self.line("    fn client_state() -> BindingResult<&'static ClientState> {");
        self.line(
            "        static STATE: std::sync::OnceLock<ClientState> = std::sync::OnceLock::new();",
        );
        self.line("        if let Some(state) = STATE.get() {");
        self.line("            return Ok(state);");
        self.line("        }");
        self.line("        let state = ClientState::open()?;");
        self.line("        let _ = STATE.set(state);");
        self.line("        Ok(STATE.get().expect(\"client state was just initialized\"))");
        self.line("    }");
        self.line("");
        self.line(&format!("    pub struct {}Service;", service.name));
        self.line("");
        if service
            .items
            .iter()
            .any(|item| matches!(item, ServiceItem::Store(_)))
        {
            self.client_store_event_type();
        }
        for store in service.items.iter().filter_map(as_store) {
            self.client_store_type(store);
        }
        self.line(&format!("    impl {}Service {{", service.name));
        self.line("");
        self.client_anonymous_store_methods();
        for function in service.items.iter().filter_map(as_function) {
            self.client_function(function);
        }
        self.client_next_message_method();
        self.client_wait_reply_method();
        self.line("    }");
        self.line("");
        self.client_super_next_message_function();
    }

    fn client_store_event_type(&mut self) {
        self.line("    #[derive(Clone, Debug, PartialEq)]");
        self.line("    pub enum StoreEvent<T> {");
        self.line("        Accepted { value: T, last_updated_timestamp: isize },");
        self.line("        Updated(T),");
        self.line("        Rejected { message: motherboard_client::Str },");
        self.line("        Closed { reason: motherboard_client::CloseReason },");
        self.line("    }");
        self.line("");
    }

    fn client_store_type(&mut self, store: &Store) {
        let snake = snake_case(&store.name);
        let type_name = format!("{}Store", pascal_case(&snake));
        let subscription_type = format!("{type_name}Subscription");
        let const_name = format!("{}_STORE", screaming_snake_case(&store.name));
        let ty = rust_type(&store.ty);
        self.line(&format!("    pub struct {type_name};"));
        self.line("");
        self.line("    #[derive(Clone, Copy, Debug, Eq, PartialEq)]");
        self.line(&format!("    pub struct {subscription_type} {{"));
        self.line("        pub id: motherboard_client::SubscriptionId,");
        self.line("    }");
        self.line("");
        self.line(&format!("    impl {type_name} {{"));
        self.line(&format!(
            "        pub async fn subscribe() -> BindingResult<{subscription_type}> {{"
        ));
        self.line("            let state = client_state()?;");
        self.line(&format!(
            "            state.motherboard.client().stores().subscribe(SERVICE, {const_name}).map(|id| {subscription_type} {{ id }}).map_err(BindingError::from)"
        ));
        self.line("        }");
        self.line("");
        self.line(&format!(
            "        pub async fn next_event(subscription: &{subscription_type}) -> BindingResult<StoreEvent<{ty}>> {{"
        ));
        self.line("            loop {");
        self.line("                let state = client_state()?;");
        self.line("                let mut deferred = std::collections::VecDeque::new();");
        self.line("                {");
        self.line("                    let mut messages = state.messages.lock().await;");
        self.line("                    while let Some(message) = messages.pop_front() {");
        self.line(&format!(
            "                        match decode_{snake}_store_event(message, subscription.id)? {{"
        ));
        self.line("                            Ok(event) => {");
        self.line("                                while let Some(message) = deferred.pop_back() { messages.push_front(message); }");
        self.line("                                return Ok(event);");
        self.line("                            }");
        self.line("                            Err(message) => deferred.push_back(message),");
        self.line("                        }");
        self.line("                    }");
        self.line("                    while let Some(message) = deferred.pop_back() { messages.push_front(message); }");
        self.line("                }");
        self.line("                let message = super_next_message().await?;");
        self.line(&format!(
            "                match decode_{snake}_store_event(message, subscription.id)? {{"
        ));
        self.line("                    Ok(event) => return Ok(event),");
        self.line("                    Err(message) => client_state()?.messages.lock().await.push_back(message),");
        self.line("                }");
        self.line("            }");
        self.line("        }");
        self.line("");
        self.line(&format!(
            "        pub async fn unsubscribe(subscription: {subscription_type}) -> BindingResult<()> {{"
        ));
        self.line("            let state = client_state()?;");
        self.line("            state.motherboard.client().stores().unsubscribe(subscription.id).map_err(BindingError::from)");
        self.line("        }");
        self.line("    }");
        self.line("");
        self.line(&format!(
            "    fn decode_{snake}_store_event(message: motherboard_client::InboxMessage, subscription_id: motherboard_client::SubscriptionId) -> BindingResult<Result<StoreEvent<{ty}>, motherboard_client::InboxMessage>> {{"
        ));
        self.line("        match message {");
        self.line("            motherboard_client::InboxMessage::StoreSubscriptionAccepted { service, store, subscription_id: received_subscription_id, current_value, last_updated_timestamp }");
        self.line(&format!(
            "                if service.as_str() == SERVICE && store.as_str() == {const_name} && received_subscription_id == subscription_id => {{"
        ));
        self.line("                    postcard::from_bytes(&current_value)");
        self.line("                        .map(|value| Ok(StoreEvent::Accepted { value, last_updated_timestamp }))");
        self.line("                        .map_err(BindingError::Decode)");
        self.line("                }");
        self.line("            motherboard_client::InboxMessage::StoreSubscriptionUpdated { service, store, subscription_id: received_subscription_id, payload }");
        self.line(&format!(
            "                if service.as_str() == SERVICE && store.as_str() == {const_name} && received_subscription_id == subscription_id => {{"
        ));
        self.line("                    postcard::from_bytes(&payload).map(|value| Ok(StoreEvent::Updated(value))).map_err(BindingError::Decode)");
        self.line("                }");
        self.line("            motherboard_client::InboxMessage::StoreSubscriptionRejected { service, store, subscription_id: received_subscription_id, message }");
        self.line(&format!(
            "                if service.as_str() == SERVICE && store.as_str() == {const_name} && received_subscription_id == subscription_id => {{"
        ));
        self.line("                    Ok(Ok(StoreEvent::Rejected { message }))");
        self.line("                }");
        self.line("            motherboard_client::InboxMessage::StoreSubscriptionClosed { service, store, subscription_id: received_subscription_id, reason }");
        self.line(&format!(
            "                if service.as_str() == SERVICE && store.as_str() == {const_name} && received_subscription_id == subscription_id => {{"
        ));
        self.line("                    Ok(Ok(StoreEvent::Closed { reason }))");
        self.line("                }");
        self.line("            message => Ok(Err(message)),");
        self.line("        }");
        self.line("    }");
        self.line("");
    }

    fn client_anonymous_store_methods(&mut self) {
        self.line("        pub async fn subscribe_anonymous_store<T>(store: AnonymousStore<T>) -> BindingResult<motherboard_client::SubscriptionId> {");
        self.line("            let state = client_state()?;");
        self.line("            state.motherboard.client().stores().subscribe_anonymous(store.id).map_err(BindingError::from)");
        self.line("        }");
        self.line("");
        self.line("        pub async fn unsubscribe(subscription_id: motherboard_client::SubscriptionId) -> BindingResult<()> {");
        self.line("            let state = client_state()?;");
        self.line("            state.motherboard.client().stores().unsubscribe(subscription_id).map_err(BindingError::from)");
        self.line("        }");
        self.line("");
    }

    fn client_function(&mut self, function: &Function) {
        self.docs_indented(&function.docs, 8);
        let params = function
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name, rust_type(&p.ty)))
            .collect::<Vec<_>>()
            .join(", ");
        let return_ty = client_function_return_type(function);
        self.line(&format!(
            "        pub async fn {}({params}) -> BindingResult<{return_ty}> {{",
            function.name
        ));
        self.line(&format!(
            "            let payload = postcard::to_allocvec(&{}).map_err(BindingError::Encode)?;",
            payload_tuple_expr(&function.params)
        ));
        self.line("            let state = client_state()?;");
        self.line(&format!(
            "            let request_id = state.motherboard.client().calls().call(SERVICE, {:?}, payload.into_boxed_slice(), Box::<[motherboard_client::RawFd]>::default()).map_err(BindingError::from)?;",
            function.name
        ));
        self.line("            let message = Self::wait_for_reply(state, request_id).await?;");
        self.line("            match message {");
        self.line("                motherboard_client::InboxMessage::FunctionCallReply { status: motherboard_client::ReplyStatus::Ok, payload, .. } => {");
        self.line(&format!(
            "                    decode_{}_reply(&payload)",
            function.name
        ));
        self.line("                }");
        self.line("                motherboard_client::InboxMessage::FunctionCallReply { status: motherboard_client::ReplyStatus::Error { .. }, .. } => Err(BindingError::UnexpectedReply),");
        self.line("                _ => Err(BindingError::UnexpectedReply),");
        self.line("            }");
        self.line("        }");
        self.line("");
    }

    fn client_next_message_method(&mut self) {
        self.line("        pub async fn next_message() -> BindingResult<motherboard_client::InboxMessage> {");
        self.line("            super_next_message().await");
        self.line("        }");
        self.line("");
    }

    fn client_super_next_message_function(&mut self) {
        self.line("    async fn super_next_message() -> BindingResult<motherboard_client::InboxMessage> {");
        self.line("        let state = client_state()?;");
        self.line("        if let Some(message) = state.messages.lock().await.pop_front() {");
        self.line("            return Ok(message);");
        self.line("        }");
        self.line("        let _guard = state.fetch_lock.lock().await;");
        self.line("        loop {");
        self.line("            if let Some(message) = state.messages.lock().await.pop_front() {");
        self.line("                return Ok(message);");
        self.line("            }");
        self.line("            let message = state.motherboard.client().fetch_async().await.map_err(BindingError::from)?;");
        self.line("            match &message {");
        self.line("                motherboard_client::InboxMessage::FunctionCallReply { request_id, .. } => {");
        self.line("                    state.replies.lock().await.insert(*request_id, message);");
        self.line("                }");
        self.line("                _ => return Ok(message),");
        self.line("            }");
        self.line("        }");
        self.line("    }");
        self.line("");
    }

    fn client_wait_reply_method(&mut self) {
        self.line("        async fn wait_for_reply(state: &ClientState, request_id: motherboard_client::RequestId) -> BindingResult<motherboard_client::InboxMessage> {");
        self.line(
            "            if let Some(message) = state.replies.lock().await.remove(&request_id) {",
        );
        self.line("                return Ok(message);");
        self.line("            }");
        self.line("            let _guard = state.fetch_lock.lock().await;");
        self.line("            loop {");
        self.line("                if let Some(message) = state.replies.lock().await.remove(&request_id) {");
        self.line("                    return Ok(message);");
        self.line("                }");
        self.line("                let message = state.motherboard.client().fetch_async().await.map_err(BindingError::from)?;");
        self.line("                match &message {");
        self.line("                    motherboard_client::InboxMessage::FunctionCallReply { request_id: reply_id, .. } if *reply_id == request_id => return Ok(message),");
        self.line("                    motherboard_client::InboxMessage::FunctionCallReply { request_id: reply_id, .. } => {");
        self.line("                        state.replies.lock().await.insert(*reply_id, message);");
        self.line("                    }");
        self.line("                    _ => {");
        self.line("                        state.messages.lock().await.push_back(message);");
        self.line("                    }");
        self.line("                }");
        self.line("            }");
        self.line("        }");
        self.line("");
    }

    fn server_wrapper(&mut self, service: &Service) {
        self.server_trait_runtime(service);
        self.line(&format!("    pub struct {}Server<'a> {{", service.name));
        self.line("        motherboard: &'a motherboard_client::MotherboardClient,");
        self.line("        anonymous_authorizers: std::sync::Arc<std::sync::Mutex<std::collections::HashMap<motherboard_client::AnonymousStoreId, super::AnonymousStoreAuthorizer>>>,");
        self.line("    }");
        self.line("");
        self.line(&format!("    impl Clone for {}Server<'_> {{", service.name));
        self.line("        fn clone(&self) -> Self {");
        self.line("            Self { motherboard: self.motherboard, anonymous_authorizers: self.anonymous_authorizers.clone() }");
        self.line("        }");
        self.line("    }");
        self.line("");
        self.line(&format!("    impl<'a> {}Server<'a> {{", service.name));
        self.line(
            "        pub fn new(motherboard: &'a motherboard_client::MotherboardClient) -> Self {",
        );
        self.line("            Self { motherboard, anonymous_authorizers: Default::default() }");
        self.line("        }");
        self.line("");
        self.line("        pub fn bind(&self) -> BindingResult<()> {");
        self.line("            self.motherboard.server().bind_service(SERVICE).map_err(BindingError::from)");
        self.line("        }");
        self.line("");
        self.line("        pub fn spawn_request<H, Fut>(&self, message: motherboard_client::InboxMessage, handler: H) -> BindingResult<bool>");
        self.line("        where");
        self.line("            H: FnOnce(Request, motherboard_client::ReplyToken, motherboard_client::Origin) -> Fut + Send + 'static,");
        self.line("            Fut: core::future::Future<Output = ()> + Send + 'static,");
        self.line("        {");
        self.line("            match message {");
        self.line("                motherboard_client::InboxMessage::FunctionCallRequest { service, method, reply_token, origin, payload, .. } if service.as_str() == SERVICE => {");
        self.line("                    let Some(request) = decode_request(&method, &payload)? else { return Ok(false); };");
        self.line("                    tokio::spawn(async move { handler(request, reply_token, origin).await; });");
        self.line("                    Ok(true)");
        self.line("                }");
        self.line("                _ => Ok(false),");
        self.line("            }");
        self.line("        }");
        self.line("");
        self.line("        pub fn authorize_anonymous_subscription(&self, message: motherboard_client::InboxMessage) -> BindingResult<bool> {");
        self.line("            match message {");
        self.line("                motherboard_client::InboxMessage::AnonymousStoreSubscribeRequest { id, reply_token, origin, .. } => {");
        self.line("                    let authorizer = self.anonymous_authorizers.lock().expect(\"anonymous store authorizer lock poisoned\").get(&id).cloned();");
        self.line("                    if let Some(authorizer) = authorizer {");
        self.line("                        if authorizer(origin) {");
        self.line("                            self.motherboard.server().stores().accept_subscription(reply_token).map_err(BindingError::from)?;");
        self.line("                        } else {");
        self.line("                            self.motherboard.server().stores().reject_subscription(reply_token, \"PermissionDenied\").map_err(BindingError::from)?;");
        self.line("                        }");
        self.line("                    } else {");
        self.line("                        self.motherboard.server().stores().reject_subscription(reply_token, \"NoSuchAnonymousStoreAuthorizer\").map_err(BindingError::from)?;");
        self.line("                    }");
        self.line("                    Ok(true)");
        self.line("                }");
        self.line("                _ => Ok(false),");
        self.line("            }");
        self.line("        }");
        self.line("");
        for store in service.items.iter().filter_map(as_store) {
            self.server_store_methods(store);
        }
        for function in service.items.iter().filter_map(as_function) {
            if let Some(inner) = anonymous_store_inner(&function.returns) {
                self.server_anonymous_store_methods(function, inner);
            }
            self.server_reply_method(function);
        }
        self.line("    }");
        self.line("");
    }

    fn server_trait_runtime(&mut self, service: &Service) {
        let trait_name = if self.mode == RustMode::Server {
            format!("{}Service", service.name)
        } else {
            format!("{}ServiceHandler", service.name)
        };
        let context_name = format!("{}Context", service.name);
        self.line(&format!("    pub struct {context_name}<'a> {{"));
        self.line(&format!(
            "        pub(crate) server: {}Server<'a>,",
            service.name
        ));
        self.line("        pub(crate) anonymous_kinds: std::sync::Arc<std::sync::Mutex<std::collections::HashMap<motherboard_client::AnonymousStoreId, &'static str>>>,");
        self.line("    }");
        self.line("");
        self.line(&format!("    impl<'a> {context_name}<'a> {{"));
        for store in service.items.iter().filter_map(as_store) {
            let snake = snake_case(&store.name);
            let ty = rust_type(&store.ty);
            self.line(&format!(
                "        pub async fn create_{snake}_store(&mut self, initial_value: {ty}) -> BindingResult<()> {{"
            ));
            self.line(&format!(
                "            self.server.create_{snake}_store(&initial_value)"
            ));
            self.line("        }");
            self.line("");
            self.line(&format!(
                "        pub async fn update_{snake}_store(&mut self, value: {ty}) -> BindingResult<()> {{"
            ));
            self.line(&format!(
                "            self.server.update_{snake}_store(&value)"
            ));
            self.line("        }");
            self.line("");
        }
        for function in service.items.iter().filter_map(as_function) {
            if let Some(inner) = anonymous_store_inner(&function.returns) {
                let snake = snake_case(&function.name);
                let value_ty = rust_type(inner);
                let store_ty = rust_type(&function.returns);
                let result_ty = server_trait_return_type(function, &store_ty);
                self.line(&format!(
                    "        pub async fn create_{snake}_store(&mut self, initial_value: {value_ty}) -> {result_ty} {{"
                ));
                self.line(&format!("            let store = self.server.create_{snake}_store(&initial_value, |_origin| false).expect(\"failed to create anonymous store\");"));
                self.line(&format!(
                    "            self.anonymous_kinds.lock().expect(\"anonymous kind lock poisoned\").insert(store.id, {:?});",
                    function.name
                ));
                if function.errors.is_empty() {
                    self.line("            Ok(store)");
                } else {
                    self.line("            Ok(store)");
                }
                self.line("        }");
                self.line("");
                self.line(&format!(
                    "        pub async fn update_{snake}_store(&mut self, store: {store_ty}, value: {value_ty}) -> BindingResult<()> {{"
                ));
                self.line(&format!(
                    "            self.server.update_{snake}_store(store, &value)"
                ));
                self.line("        }");
                self.line("");
            }
        }
        self.line("    }");
        self.line("");

        self.line("    #[async_trait::async_trait]");
        self.line(&format!(
            "    pub trait {trait_name}: Send + Sync + 'static {{"
        ));
        for store in service.items.iter().filter_map(as_store) {
            let snake = snake_case(&store.name);
            self.docs_indented(&store.docs, 8);
            self.line(&format!(
                "        async fn initial_{snake}(&self) -> BindingResult<{}>;",
                rust_type(&store.ty)
            ));
        }
        for function in service.items.iter().filter_map(as_function) {
            self.docs_indented(&function.docs, 8);
            self.line(&format!(
                "        async fn {}(&self, ctx: &mut {}<'_>, origin: motherboard_client::Origin{}) -> {};",
                function.name,
                context_name,
                trait_params_suffix(function),
                server_trait_return_type(function, &rust_type(&function.returns))
            ));
            if anonymous_store_inner(&function.returns).is_some() {
                self.line(&format!(
                    "        async fn authorize_{}_subscription(&self, origin: motherboard_client::Origin, store: {}) -> bool;",
                    function.name,
                    rust_type(&function.returns)
                ));
            }
        }
        self.line("    }");
        self.line("");

        self.dispatch_trait_request(service, &trait_name, &context_name);
        self.dispatch_anonymous_subscription(service, &trait_name);
    }

    fn dispatch_trait_request(&mut self, service: &Service, trait_name: &str, context_name: &str) {
        self.line(&format!(
            "    pub(crate) async fn dispatch_trait_request(service: &dyn {trait_name}, ctx: &mut {context_name}<'_>, server: {server}Server<'static>, request: Request, reply_token: motherboard_client::ReplyToken, origin: motherboard_client::Origin) -> BindingResult<()> {{",
            context_name = context_name,
            server = service.name
        ));
        self.line("        match request {");
        for function in service.items.iter().filter_map(as_function) {
            let variant = pascal_case(&function.name);
            let vars = function
                .params
                .iter()
                .map(|field| field.name.as_str())
                .collect::<Vec<_>>();
            let pattern = request_payload_pattern(&vars);
            let args = if vars.is_empty() {
                String::new()
            } else {
                format!(", {}", vars.join(", "))
            };
            self.line(&format!("            Request::{variant}({pattern}) => {{"));
            if function.errors.is_empty() {
                self.line(&format!(
                    "                let value = service.{}(ctx, origin{args}).await?;",
                    function.name
                ));
                self.line(&format!(
                    "                server.reply_{}(reply_token, &value)?;",
                    function.name
                ));
            } else {
                self.line(&format!(
                    "                let value = service.{}(ctx, origin{args}).await;",
                    function.name
                ));
                self.line(&format!(
                    "                server.reply_{}(reply_token, &value)?;",
                    function.name
                ));
            }
            self.line("            }");
        }
        self.line("        }");
        self.line("        Ok(())");
        self.line("    }");
        self.line("");
    }

    fn dispatch_anonymous_subscription(&mut self, service: &Service, trait_name: &str) {
        self.line(&format!(
            "    pub(crate) async fn dispatch_anonymous_subscription(service: &dyn {trait_name}, server: {server}Server<'static>, anonymous_kinds: std::sync::Arc<std::sync::Mutex<std::collections::HashMap<motherboard_client::AnonymousStoreId, &'static str>>>, id: motherboard_client::AnonymousStoreId, reply_token: motherboard_client::ReplyToken, origin: motherboard_client::Origin) -> BindingResult<()> {{",
            server = service.name
        ));
        self.line("        let kind = anonymous_kinds.lock().expect(\"anonymous kind lock poisoned\").get(&id).copied();");
        self.line("        let accepted = match kind {");
        for function in service.items.iter().filter_map(as_function) {
            if anonymous_store_inner(&function.returns).is_some() {
                self.line(&format!(
                    "            Some({:?}) => service.authorize_{}_subscription(origin, AnonymousStore::new(id)).await,",
                    function.name,
                    function.name
                ));
            }
        }
        self.line("            _ => false,");
        self.line("        };");
        self.line("        if accepted {");
        self.line("            server.motherboard.server().stores().accept_subscription(reply_token).map_err(BindingError::from)");
        self.line("        } else {");
        self.line("            server.motherboard.server().stores().reject_subscription(reply_token, \"PermissionDenied\").map_err(BindingError::from)");
        self.line("        }");
        self.line("    }");
        self.line("");
    }

    fn server_runtime(&mut self) {
        self.line("pub struct ServerRuntime {");
        self.line("    motherboard: &'static motherboard_client::MotherboardClient,");
        for service in &self.document.services {
            self.line(&format!(
                "    {}: Option<Installed{}>,",
                snake_case(&service.name),
                service.name
            ));
        }
        self.line("}");
        self.line("");

        for service in &self.document.services {
            let module = snake_case(&service.name);
            let trait_name = server_trait_name_for_mode(service, self.mode);
            self.line(&format!("struct Installed{} {{", service.name));
            self.line(&format!(
                "    service: std::sync::Arc<dyn {module}::{trait_name}>,"
            ));
            self.line(&format!(
                "    server: {module}::{}Server<'static>,",
                service.name
            ));
            self.line("    anonymous_kinds: std::sync::Arc<std::sync::Mutex<std::collections::HashMap<motherboard_client::AnonymousStoreId, &'static str>>>,");
            self.line("}");
            self.line("");
        }

        self.line("impl ServerRuntime {");
        self.line("    pub fn new() -> BindingResult<Self> {");
        self.line("        let motherboard = Box::leak(Box::new(motherboard_client::MotherboardClient::open().map_err(motherboard_client::ClientError::Io)?));");
        self.line("        Ok(Self {");
        self.line("            motherboard,");
        for service in &self.document.services {
            self.line(&format!("            {}: None,", snake_case(&service.name)));
        }
        self.line("        })");
        self.line("    }");
        self.line("");

        for service in &self.document.services {
            self.install_service_method(service);
        }

        self.line("    pub async fn serve(self) -> BindingResult<()> {");
        self.line("        loop {");
        self.line("            let message = self.motherboard.server().fetch_async().await.map_err(BindingError::from)?;");
        self.line("            match message {");
        self.line("                motherboard_client::InboxMessage::FunctionCallRequest { service, method, reply_token, origin, payload, .. } => {");
        self.line("                    match service.as_str() {");
        for service in &self.document.services {
            let module = snake_case(&service.name);
            let field = snake_case(&service.name);
            self.line(&format!("                        {module}::SERVICE => {{"));
            self.line(&format!("                            let Some(installed) = &self.{field} else {{ continue; }};"));
            self.line(&format!("                            let Some(request) = {module}::decode_request(&method, &payload)? else {{ continue; }};"));
            self.line("                            let service = installed.service.clone();");
            self.line("                            let server = installed.server.clone();");
            self.line("                            let anonymous_kinds = installed.anonymous_kinds.clone();");
            self.line("                            tokio::spawn(async move {");
            self.line(&format!("                                let mut ctx = {module}::{}Context {{ server: server.clone(), anonymous_kinds }};", service.name));
            self.line(&format!("                                if let Err(error) = {module}::dispatch_trait_request(service.as_ref(), &mut ctx, server, request, reply_token, origin).await {{"));
            self.line("                                    eprintln!(\"midl server dispatch failed: {error}\");");
            self.line("                                }");
            self.line("                            });");
            self.line("                        }");
        }
        self.line("                        _ => {}");
        self.line("                    }");
        self.line("                }");
        self.line("                motherboard_client::InboxMessage::AnonymousStoreSubscribeRequest { id, reply_token, origin, .. } => {");
        for service in &self.document.services {
            let module = snake_case(&service.name);
            let field = snake_case(&service.name);
            self.line(&format!(
                "                    if let Some(installed) = &self.{field} {{"
            ));
            self.line("                        if installed.anonymous_kinds.lock().expect(\"anonymous kind lock poisoned\").contains_key(&id) {");
            self.line("                            let service = installed.service.clone();");
            self.line("                            let server = installed.server.clone();");
            self.line("                            let anonymous_kinds = installed.anonymous_kinds.clone();");
            self.line("                            tokio::spawn(async move {");
            self.line(&format!("                                if let Err(error) = {module}::dispatch_anonymous_subscription(service.as_ref(), server, anonymous_kinds, id, reply_token, origin).await {{"));
            self.line("                                    eprintln!(\"midl anonymous subscription dispatch failed: {error}\");");
            self.line("                                }");
            self.line("                            });");
            self.line("                            continue;");
            self.line("                        }");
            self.line("                    }");
        }
        self.line("                    self.motherboard.server().stores().reject_subscription(reply_token, \"NoSuchAnonymousStore\").map_err(BindingError::from)?;");
        self.line("                }");
        self.line("                _ => {}");
        self.line("            }");
        self.line("        }");
        self.line("    }");
        self.line("}");
        self.line("");
    }

    fn install_service_method(&mut self, service: &Service) {
        let module = snake_case(&service.name);
        let field = snake_case(&service.name);
        let trait_name = server_trait_name_for_mode(service, self.mode);
        self.line(&format!(
            "    pub async fn install_{field}<S: {module}::{trait_name}>(&mut self, service: S) -> BindingResult<()> {{"
        ));
        self.line(&format!(
            "        let service: std::sync::Arc<dyn {module}::{trait_name}> = std::sync::Arc::new(service);"
        ));
        self.line(&format!(
            "        let server = {module}::{}Server::new(self.motherboard);",
            service.name
        ));
        self.line("        server.bind()?;");
        self.line("        let anonymous_kinds = std::sync::Arc::new(std::sync::Mutex::new(std::collections::HashMap::new()));");
        self.line(&format!(
            "        let mut ctx = {module}::{}Context {{ server: server.clone(), anonymous_kinds: anonymous_kinds.clone() }};",
            service.name
        ));
        for store in service.items.iter().filter_map(as_store) {
            let snake = snake_case(&store.name);
            self.line(&format!(
                "        ctx.create_{snake}_store(service.initial_{snake}().await?).await?;"
            ));
        }
        self.line(&format!(
            "        self.{field} = Some(Installed{} {{ service, server, anonymous_kinds }});",
            service.name
        ));
        self.line("        Ok(())");
        self.line("    }");
        self.line("");
    }

    fn server_store_methods(&mut self, store: &Store) {
        let rust_ty = rust_type(&store.ty);
        let snake = snake_case(&store.name);
        let const_name = format!("{}_STORE", screaming_snake_case(&store.name));
        let public_name = format!("{}_STORE_PUBLIC", screaming_snake_case(&store.name));
        self.line(&format!(
            "        pub fn create_{snake}_store(&self, initial_value: &{rust_ty}) -> BindingResult<()> {{"
        ));
        self.line("            let payload = postcard::to_allocvec(initial_value).map_err(BindingError::Encode)?;");
        self.line(&format!(
            "            self.motherboard.server().stores().create(SERVICE, {const_name}, payload.into_boxed_slice(), {public_name}).map_err(BindingError::from)"
        ));
        self.line("        }");
        self.line("");
        self.line(&format!(
            "        pub fn update_{snake}_store(&self, value: &{rust_ty}) -> BindingResult<()> {{"
        ));
        self.line("            let payload = postcard::to_allocvec(value).map_err(BindingError::Encode)?;");
        self.line(&format!(
            "            self.motherboard.server().stores().update(SERVICE, {const_name}, payload.into_boxed_slice()).map_err(BindingError::from)"
        ));
        self.line("        }");
        self.line("");
    }

    fn server_reply_method(&mut self, function: &Function) {
        self.line(&format!(
            "        pub fn reply_{}(&self, reply_token: motherboard_client::ReplyToken, value: &{}) -> BindingResult<()> {{",
            function.name,
            wire_reply_type(function)
        ));
        self.line("            let payload = postcard::to_allocvec(value).map_err(BindingError::Encode)?;");
        self.line("            self.motherboard.server().calls().reply(reply_token, motherboard_client::ReplyStatus::Ok, payload.into_boxed_slice(), Box::<[motherboard_client::RawFd]>::default()).map_err(BindingError::from)");
        self.line("        }");
        self.line("");
    }

    fn server_anonymous_store_methods(&mut self, function: &Function, value_ty: &Type) {
        let snake = snake_case(&function.name);
        let rust_value_ty = rust_type(value_ty);
        let rust_store_ty = rust_type(&function.returns);
        self.line(&format!(
            "        pub fn create_{snake}_store<A>(&self, initial_value: &{rust_value_ty}, authorize: A) -> BindingResult<{rust_store_ty}>"
        ));
        self.line("        where");
        self.line("            A: Fn(motherboard_client::Origin) -> bool + Send + Sync + 'static,");
        self.line("        {");
        self.line("            let payload = postcard::to_allocvec(initial_value).map_err(BindingError::Encode)?;");
        self.line("            let id = self.motherboard.server().stores().create_anonymous(SERVICE, payload.into_boxed_slice()).map_err(BindingError::from)?;");
        self.line("            self.anonymous_authorizers.lock().expect(\"anonymous store authorizer lock poisoned\").insert(id, std::sync::Arc::new(authorize));");
        self.line("            Ok(AnonymousStore::new(id))");
        self.line("        }");
        self.line("");
        self.line(&format!(
            "        pub fn update_{snake}_store(&self, store: {rust_store_ty}, value: &{rust_value_ty}) -> BindingResult<()> {{"
        ));
        self.line("            let payload = postcard::to_allocvec(value).map_err(BindingError::Encode)?;");
        self.line("            self.motherboard.server().stores().update_anonymous(store.id, payload.into_boxed_slice()).map_err(BindingError::from)");
        self.line("        }");
        self.line("");
    }

    fn request_enum(&mut self, service: &Service) {
        self.line("    #[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]");
        self.line("    pub enum Request {");
        for function in service.items.iter().filter_map(as_function) {
            self.line(&format!(
                "        {}({}),",
                pascal_case(&function.name),
                payload_tuple_type(&function.params)
            ));
        }
        self.line("    }");
        self.line("");
        self.line("    pub fn decode_request(method: &str, payload: &[u8]) -> BindingResult<Option<Request>> {");
        self.line("        match method {");
        for function in service.items.iter().filter_map(as_function) {
            self.line(&format!(
                "            {:?} => postcard::from_bytes::<{}>(payload).map(|payload| Some(Request::{}(payload))).map_err(BindingError::Decode),",
                function.name,
                payload_tuple_type(&function.params),
                pascal_case(&function.name)
            ));
        }
        self.line("            _ => Ok(None),");
        self.line("        }");
        self.line("    }");
        self.line("");
    }

    fn reply_decoders(&mut self, service: &Service) {
        for function in service.items.iter().filter_map(as_function) {
            self.line(&format!(
                "    pub fn decode_{}_reply(payload: &[u8]) -> BindingResult<{}> {{",
                function.name,
                wire_reply_type(function)
            ));
            self.line("        postcard::from_bytes(payload).map_err(BindingError::Decode)");
            self.line("    }");
            self.line("");
        }
    }

    fn docs(&mut self, docs: &[String], indent: usize) {
        self.docs_indented(docs, indent);
    }

    fn docs_indented(&mut self, docs: &[String], indent: usize) {
        let prefix = " ".repeat(indent);
        for doc in docs {
            self.line(&format!(
                "{prefix}///{space}{doc}",
                space = if doc.is_empty() { "" } else { " " }
            ));
        }
    }

    fn line(&mut self, line: &str) {
        self.out.push_str(line);
        self.out.push('\n');
    }
}

fn as_function(item: &ServiceItem) -> Option<&Function> {
    match item {
        ServiceItem::Function(function) => Some(function),
        _ => None,
    }
}

fn as_store(item: &ServiceItem) -> Option<&Store> {
    match item {
        ServiceItem::Store(store) => Some(store),
        _ => None,
    }
}

fn anonymous_store_inner(ty: &Type) -> Option<&Type> {
    match ty {
        Type::AnonymousStore(inner) => Some(inner),
        _ => None,
    }
}

fn rust_type(ty: &Type) -> String {
    match ty {
        Type::Named(name) => match name.as_str() {
            "string" => "String".to_string(),
            primitive => primitive.to_string(),
        },
        Type::Array(inner) => format!("Vec<{}>", rust_type(inner)),
        Type::Tuple(items) => {
            if items.is_empty() {
                "()".to_string()
            } else {
                format!(
                    "({})",
                    items.iter().map(rust_type).collect::<Vec<_>>().join(", ")
                )
            }
        }
        Type::AnonymousStore(inner) => format!("AnonymousStore<{}>", rust_type(inner)),
        Type::Void => "()".to_string(),
    }
}

fn client_function_return_type(function: &Function) -> String {
    wire_reply_type(function)
}

fn wire_reply_type(function: &Function) -> String {
    let ok = rust_type(&function.returns);
    if function.errors.is_empty() {
        ok
    } else {
        format!("Result<{ok}, {}Error>", pascal_case(&function.name))
    }
}

fn server_trait_return_type(function: &Function, ok: &str) -> String {
    if function.errors.is_empty() {
        format!("BindingResult<{ok}>")
    } else {
        format!("Result<{ok}, {}Error>", pascal_case(&function.name))
    }
}

fn server_trait_name_for_mode(service: &Service, mode: RustMode) -> String {
    if mode == RustMode::Server {
        format!("{}Service", service.name)
    } else {
        format!("{}ServiceHandler", service.name)
    }
}

fn trait_params_suffix(function: &Function) -> String {
    let params = function
        .params
        .iter()
        .map(|field| format!(", {}: {}", field.name, rust_type(&field.ty)))
        .collect::<String>();
    params
}

fn request_payload_pattern(vars: &[&str]) -> String {
    match vars {
        [] => "()".to_string(),
        [single] => format!("({single},)"),
        vars => format!("({})", vars.join(", ")),
    }
}

fn payload_tuple_type(params: &[Field]) -> String {
    match params {
        [] => "()".to_string(),
        [field] => format!("({},)", rust_type(&field.ty)),
        fields => format!(
            "({})",
            fields
                .iter()
                .map(|field| rust_type(&field.ty))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

fn payload_tuple_expr(params: &[Field]) -> String {
    match params {
        [] => "()".to_string(),
        [field] => format!("({},)", field.name),
        fields => format!(
            "({})",
            fields
                .iter()
                .map(|field| field.name.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

fn snake_case(name: &str) -> String {
    let mut out = String::new();
    let mut prev_was_lower_or_digit = false;
    for ch in name.chars() {
        if ch == '_' {
            out.push('_');
            prev_was_lower_or_digit = false;
        } else if ch.is_ascii_uppercase() {
            if prev_was_lower_or_digit {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
            prev_was_lower_or_digit = false;
        } else {
            out.push(ch);
            prev_was_lower_or_digit = ch.is_ascii_lowercase() || ch.is_ascii_digit();
        }
    }
    out
}

fn screaming_snake_case(name: &str) -> String {
    snake_case(name).to_ascii_uppercase()
}

fn pascal_case(name: &str) -> String {
    let mut out = String::new();
    let mut upper_next = true;
    for ch in name.chars() {
        if ch == '_' {
            upper_next = true;
        } else if upper_next {
            out.push(ch.to_ascii_uppercase());
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}
